[package]
name = "cyclonedds-rs"
version = "0.1.0"
authors = ["Sojan James <Sojan.James@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cyclonedds-sys = { path = "../cyclonedds-sys" }
either = "1.5"
bit_field = "0.10"

